//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FireLearn.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKurs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblKurs()
        {
            this.tblKelime = new HashSet<tblKelime>();
            this.tblTamamlanan = new HashSet<tblTamamlanan>();
        }
    
        public int kursID { get; set; }
        public string kursAdi { get; set; }
        public Nullable<int> kursDerece { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKelime> tblKelime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTamamlanan> tblTamamlanan { get; set; }
    }
}
