//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FireLearn.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKelime
    {
        public int kelimeID { get; set; }
        public string kelimeTR { get; set; }
        public string kelimeING { get; set; }
        public string kelimeTuru { get; set; }
        public Nullable<int> kelimeDerece { get; set; }
        public string kelimevideo { get; set; }
    
        public virtual tblKurs tblKurs { get; set; }
    }
}
