//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FireLearn.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTamamlanan
    {
        public int tamamlanankursID { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> kursID { get; set; }
    
        public virtual tblKurs tblKurs { get; set; }
        public virtual tblUsers tblUsers { get; set; }
    }
}
